# Generated by Django 4.0.4 on 2022-05-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_alter_attendance_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp623', max_length=70),
        ),
    ]
