# Generated by Django 4.0.4 on 2022-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_alter_employee_emp_id_alter_employee_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='RAK Bank ', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp455', max_length=70),
        ),
    ]
